// One shared premium footer across every page.
function renderSiteFooter(){
  if(document.body.classList.contains('error-page'))return;
  const icon=(name,path)=>`<svg viewBox="0 0 24 24" role="img" aria-label="${name}"><path d="${path}"/></svg>`;
  const social=[
    ['Instagram','M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5Zm0 2a3 3 0 0 0-3 3v10a3 3 0 0 0 3 3h10a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3H7Zm5 3a5 5 0 1 1 0 10 5 5 0 0 1 0-10Zm0 2a3 3 0 1 0 0 6 3 3 0 0 0 0-6Zm5.5-3.2a1.2 1.2 0 1 1 0 2.4 1.2 1.2 0 0 1 0-2.4Z'],
    ['YouTube','M21.6 7.2a3 3 0 0 0-2.1-2.1C17.6 4.6 12 4.6 12 4.6s-5.6 0-7.5.5a3 3 0 0 0-2.1 2.1A31 31 0 0 0 2 12a31 31 0 0 0 .4 4.8 3 3 0 0 0 2.1 2.1c1.9.5 7.5.5 7.5.5s5.6 0 7.5-.5a3 3 0 0 0 2.1-2.1A31 31 0 0 0 22 12a31 31 0 0 0-.4-4.8ZM10 15.4V8.6l6 3.4-6 3.4Z'],
    ['X','M18.9 2H22l-6.8 7.8L23.2 22H17l-4.9-6.4L6.5 22H3.4l7.3-8.4L3 2h6.3l4.4 5.8L18.9 2Zm-1.1 17.8h1.7L8.4 4.1H6.6l11.2 15.7Z'],
    ['Facebook','M14 8h4V3.2c-.7-.1-2.2-.2-4-.2-4 0-6.7 2.4-6.7 6.8V14H3v5.4h4.3V24h5.3v-4.6H17l.7-5.4h-5.1v-3.7C12.6 8.8 13 8 14 8Z']
  ];
  const footer=document.querySelector('footer')||document.createElement('footer');
  footer.className='premium-footer';
  footer.innerHTML=`<div class="footer-shell"><div class="footer-main"><div class="footer-intro"><a href="index.html" aria-label="Stackly home"><img class="site-logo footer-logo" src="assets/stackly-logo.webp" alt="Stackly"></a><p>Your premium destination for cinematic games, expert hardware, and a community that never stops playing.</p><div class="premium-socials">${social.map(([n,p])=>`<a href="404.html" aria-label="${n}">${icon(n,p)}</a>`).join('')}</div></div><div class="footer-column"><h3>Quick Links</h3><a href="index.html">Home</a><a href="about.html">About Us</a><a href="index.html#catalog">Games</a><a href="services.html">Services</a><a href="blog.html">Blog</a><a href="contact.html">Contact</a></div><div class="footer-column"><h3>Services</h3><a href="services.html">Custom Builds</a><a href="services.html">Repairs</a><a href="services.html">Game Coaching</a><a href="contact.html">Customer Support</a></div><div class="footer-column"><h3>Help & Legal</h3><a href="404.html">Help Centre</a><a href="404.html">Account</a><a href="404.html">Terms of Use</a><a href="404.html">Privacy</a></div><div class="footer-newsletter"><h3>Stay in the Game</h3><p>Weekly releases, hardware guides, and members-only drops.</p><form class="footer-subscribe-form"><label class="sr-only" for="footerEmail">Email address</label><input id="footerEmail" type="email" placeholder="Email address" required><button type="submit" aria-label="Subscribe">→</button></form><small>No spam. Unsubscribe anytime.</small></div></div><div class="footer-contact"><span>Questions? <a href="404.html">+91 80 4567 1234</a></span><span><a href="404.html">support@stackly.gg</a></span><span>Available 24/7</span></div><div class="footer-bottom"><span>© 2026 Stackly. All rights reserved.</span><span>India · English</span><span>Built for players.</span></div></div>`;
  if(!footer.isConnected)document.body.appendChild(footer);
  const dashboardHome=document.querySelector('.dash-side .logo')?.getAttribute('href');
  if(dashboardHome)footer.querySelector('.footer-intro>a')?.setAttribute('href',dashboardHome);
}
renderSiteFooter();
document.querySelector('.footer-subscribe-form')?.addEventListener('submit',event=>{event.preventDefault();location.href='404.html'});

// Shared Stackly page behavior.
const navToggle=document.querySelector('.nav-toggle');
navToggle?.addEventListener('click',()=>{document.querySelector('.nav-links')?.classList.toggle('open');navToggle.classList.toggle('open');document.body.classList.toggle('nav-open')});
document.querySelector('.menu')?.addEventListener('click',()=>document.body.classList.toggle('nav-open'));
const mobileNav=document.querySelector('.nav-menu,.nav-links');if(mobileNav&&!mobileNav.querySelector('.mobile-auth-menu')){const tag=mobileNav.tagName==='UL'?'li':'div';mobileNav.insertAdjacentHTML('beforeend',`<${tag} class="mobile-auth-menu"><a class="mobile-login" href="login.html">Log In</a><a class="mobile-signup" href="signup.html">Sign Up</a></${tag}>`)}
const dashSide=document.querySelector('.dash-side');if(dashSide&&!dashSide.querySelector('.dash-close'))dashSide.querySelector('.logo')?.insertAdjacentHTML('afterend','<button class="dash-close" type="button" aria-label="Close dashboard menu">×</button>');document.querySelector('.dash-close')?.addEventListener('click',()=>dashSide?.classList.remove('open'));
function openDashboardSection(hash){if(!hash||hash==='#')return;const main=document.querySelector('.dash-main'),target=document.querySelector(hash);if(!main||!target)return;const blocks=[...main.children].filter(el=>!el.classList.contains('dash-topbar'));blocks.forEach(block=>{block.hidden=true;[...block.children].forEach(child=>{if(child.id)child.hidden=false})});const directBlock=target.parentElement===main?target:target.parentElement;directBlock.hidden=false;if(target.parentElement!==main)[...directBlock.children].forEach(child=>{if(child.id)child.hidden=child!==target});if(hash==='#overview'&&target.parentElement===main){const next=target.nextElementSibling;if(next?.classList.contains('kpi-grid'))next.hidden=false}document.querySelectorAll('.dash-link').forEach(link=>link.classList.toggle('active',link.getAttribute('href')===hash));document.querySelectorAll('.dashboard-focus').forEach(el=>el.classList.remove('dashboard-focus'));target.classList.add('dashboard-focus');try{history.replaceState(null,'',hash)}catch{}setTimeout(()=>target.classList.remove('dashboard-focus'),700)}
document.querySelectorAll('.dash-link[href^="#"]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();openDashboardSection(link.getAttribute('href'));document.querySelector('.dash-side')?.classList.remove('open')}));
if(document.querySelector('.dash'))setTimeout(()=>openDashboardSection(location.hash||'#overview'),0);
document.querySelector('.profile-button')?.addEventListener('click',()=>openDashboardSection('#profile'));
addEventListener('scroll',()=>document.querySelector('.navbar')?.classList.toggle('scrolled',scrollY>24));
document.querySelectorAll('.nav-links a,.nav-menu a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('.nav-links,.nav-menu')?.classList.remove('open');document.body.classList.remove('nav-open')}));
const authModal=document.getElementById('authModal');
function setAuthTab(tab){const login=tab==='login';const loginForm=document.getElementById('formLogin'),signupForm=document.getElementById('formSignup');if(loginForm)loginForm.style.display=login?'block':'none';if(signupForm)signupForm.style.display=login?'none':'block';document.getElementById('tabLogin')?.classList.toggle('active',login);document.getElementById('tabSignup')?.classList.toggle('active',!login)}
document.querySelectorAll('[data-open-auth]').forEach(b=>b.addEventListener('click',()=>{location.href=(b.dataset.openAuth==='signup'?'signup.html':'login.html')}));
document.getElementById('tabLogin')?.addEventListener('click',()=>setAuthTab('login'));document.getElementById('tabSignup')?.addEventListener('click',()=>setAuthTab('signup'));
authModal?.addEventListener('click',e=>{if(e.target===authModal||e.target.closest('[data-close-modal]')){authModal.classList.remove('open');document.body.classList.remove('modal-open')}});
document.querySelector('.modal-close')?.addEventListener('click',()=>{authModal?.classList.remove('open');document.body.classList.remove('modal-open')});
function nameFromEmail(email){const raw=(email.split('@')[0]||'Player').replace(/[._-]+/g,' ').trim();return raw.replace(/\b\w/g,char=>char.toUpperCase())||'Player'}
document.querySelectorAll('#formLogin,#formSignup,#contactForm').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();if(form.id==='contactForm'){location.href='404.html';return}const email=form.querySelector('input[type="email"]')?.value.trim().toLowerCase()||'',enteredName=form.querySelector('#signupName')?.value.trim(),displayName=enteredName||nameFromEmail(email);try{localStorage.setItem('stacklyUser',JSON.stringify({email,displayName}))}catch{}if(form.id==='formSignup'){location.href='login.html';return}location.href=email.includes('admin')?'admin-dashboard.html':'user-dashboard.html'}));
const dashboardWelcome=document.getElementById('dashboardWelcome');if(dashboardWelcome){let user={email:'player@stackly.gg',displayName:'Player'};try{user={...user,...JSON.parse(localStorage.getItem('stacklyUser')||'{}')}}catch{}const displayName=user.displayName||nameFromEmail(user.email),initials=displayName.split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase();dashboardWelcome.textContent=`Welcome back, ${displayName} ⚡`;const avatar=document.getElementById('dashboardAvatar'),nameInput=document.getElementById('dashboardDisplayName'),emailInput=document.getElementById('dashboardEmail');if(avatar)avatar.textContent=initials||'U';if(nameInput)nameInput.value=displayName;if(emailInput)emailInput.value=user.email}
document.querySelectorAll('[data-switch-auth]').forEach(button=>button.addEventListener('click',()=>setAuthTab(button.dataset.switchAuth||'signup')));
document.querySelectorAll('[data-auth]').forEach(button=>button.addEventListener('click',()=>{location.href=button.dataset.auth==='signup'?'signup.html':'login.html'}));
document.querySelectorAll('.accordion-item>button').forEach(button=>button.addEventListener('click',()=>{const item=button.closest('.accordion-item'),panel=item.querySelector('.accordion-panel'),open=item.classList.toggle('open');button.setAttribute('aria-expanded',String(open));if(panel)panel.hidden=!open;const plus=button.querySelector('.plus');if(plus)plus.textContent=open?'−':'+'}));
document.querySelectorAll('.accordion-panel').forEach(panel=>panel.hidden=true);
const contactMessage=document.getElementById('contactMessage'),messageCount=document.getElementById('messageCount');contactMessage?.addEventListener('input',()=>{if(messageCount)messageCount.textContent=`${contactMessage.value.length} / 500`});
document.querySelectorAll('.tabs [data-filter]').forEach(button=>button.addEventListener('click',()=>{const tabs=button.closest('.tabs'),group=document.querySelector('[data-group][data-cat]')?.dataset.group,value=button.dataset.filter;if(!group)return;tabs.querySelector('.active')?.classList.remove('active');button.classList.add('active');document.querySelectorAll(`[data-group="${group}"][data-cat]`).forEach(card=>card.hidden=value!=='all'&&card.dataset.cat!==value)}));
document.querySelectorAll('body:not(.error-page) main>section,body:has(.navbar)>section').forEach(section=>section.classList.add('scroll-reveal'));
const revealObserver='IntersectionObserver'in window?new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -35px'}):null;
document.querySelectorAll('.reveal,.reveal-left,.reveal-right,.scroll-reveal').forEach(el=>revealObserver?revealObserver.observe(el):el.classList.add('visible'));
document.querySelectorAll('.benefit-grid article').forEach((card,index)=>{card.tabIndex=0;card.setAttribute('role','button');card.style.transitionDelay=`${index*55}ms`;const select=()=>{card.parentElement.querySelectorAll('article').forEach(item=>item.classList.remove('selected'));card.classList.add('selected')};card.addEventListener('click',select);card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();select()}})});
document.querySelectorAll('.quote-grid blockquote').forEach((card,index)=>card.style.transitionDelay=`${index*70}ms`);
const deviceArt=document.querySelector('.device-art');if(deviceArt&&matchMedia('(pointer:fine)').matches){deviceArt.addEventListener('pointermove',event=>{const box=deviceArt.getBoundingClientRect(),x=(event.clientX-box.left)/box.width-.5,y=(event.clientY-box.top)/box.height-.5;deviceArt.style.transform=`perspective(900px) rotateX(${-y*4}deg) rotateY(${x*5}deg)`});deviceArt.addEventListener('pointerleave',()=>deviceArt.style.transform='')}
document.querySelectorAll('[data-count]').forEach(el=>{const target=Number(el.dataset.count),suffix=el.dataset.suffix||'';let value=0;const tick=()=>{value=Math.min(target,value+Math.max(1,Math.ceil(target/35)));el.textContent=value.toLocaleString()+suffix;if(value<target)requestAnimationFrame(tick)};tick()});
addEventListener('scroll',()=>{const meter=document.querySelector('#power-meter .fill'),readout=document.querySelector('#power-meter .readout'),max=document.documentElement.scrollHeight-innerHeight,pct=max>0?Math.round(scrollY/max*100):0;if(meter)meter.style.width=pct+'%';if(readout)readout.textContent='PWR '+pct+'%'});

// Buttons with no application behavior lead to the site's fallback page.
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button||(button.closest('form')&&button.type==='submit'))return;const controlSelector='.menu,.nav-toggle,.dash-toggle,.dash-close,.profile-button,.close,.modal-close,.add,.genre-bar button,.tabs button,.accordion-item>button,[data-auth],[data-open-auth],[data-switch-auth],#tabLogin,#tabSignup,#heroInfo';if(button.matches(controlSelector))return;location.href=button.dataset.href||'404.html'});

// The home catalog and legacy content pages share this bundle. Provide an inert
// catalog shell on content pages so home-only bindings never abort the script.
if(!document.getElementById('gameRows')){const shell=document.createElement('div');shell.hidden=true;shell.innerHTML='<div id="gameRows"></div><div id="emptyState"></div><input id="searchInput"><button class="menu"></button><div class="nav-menu"></div><button id="heroInfo"></button><button id="heroPlay"></button><div id="toast"></div><div id="gameModal"><button class="close"></button><button class="add"></button><img id="modalImage"><h2 id="modalTitle"></h2><p id="modalText"></p></div>';document.body.appendChild(shell)}
const games=[
['Sky Dominion','aviation','Aviator • Combat'],['Flight Horizon','aviation','Simulator • Relaxing'],['Starwing Rebellion','aviation','Space • Combat'],['Rescue Vector','aviation','Helicopter • Co-op'],['Neon Velocity','racing','Street • Racing'],['Dirtline Legends','racing','Rally • Racing'],['Night Rider X','racing','Motorcycle • Sci-Fi'],['Neon District','action','Cyberpunk • Open World'],['Zero Protocol','action','Shooter • Tactical'],['Iron Oath','fantasy','Knight • RPG'],['Emberwing','fantasy','Dragons • Adventure'],['Wildborn','adventure','Survival • Jungle'],['Afterlight','adventure','Post-Apocalyptic • RPG'],['Deep Blue','adventure','Ocean • Exploration'],['Black Sails','adventure','Pirates • Strategy'],['Empire of Ash','action','Ancient • Combat'],['Shadow Cell','action','Stealth • Tactical'],['Titan Arena','action','Robots • Fighting'],['Exoplanet','adventure','Space • Exploration'],['Last Dawn','action','Zombies • Survival'],['Final Whistle','sports','Football • Sports'],['Hoop Dynasty','sports','Basketball • Sports'],['Boundary Kings','sports','Cricket • Sports'],['Summit Rush','sports','Snowboard • Sports'],['Fight Night Zero','sports','Boxing • Sports'],['Grand Prix Redline','racing','Formula • Racing'],['Arcade Afterdark','action','Retro • Arcade'],['Pixel Keep','fantasy','Dungeon • Roguelike'],['Orbit Command','action','Space • Strategy'],['Mechfall','action','Mechs • War'],['Dust & Honor','action','Western • Adventure'],['Blades of Kyoto','action','Samurai • Combat'],['Arcana Academy','fantasy','Magic • RPG'],['Midnight Case','adventure','Detective • Mystery'],['Blackwood Manor','adventure','Horror • Survival'],['Wasteland Convoy','racing','Desert • Action'],['Fleet Command','action','Naval • Strategy'],['City Sentinel','action','Hero • Open World'],['Green Valley','adventure','Cozy • Simulation'],['World Champions','sports','Esports • Competitive']
].map((g,i)=>({title:g[0],cat:g[1],tags:g[2],img:`assets/game-${String(i+1).padStart(2,'0')}.webp`,desc:`Enter the world of ${g[0]}, a cinematic ${g[2].toLowerCase()} experience built for players who want one more unforgettable run.`}));
const rowDefs=[['Trending Now',games.slice(0,10)],['Top 10 Games Today',games.slice(10,20)],['Aviation & Flight',games.filter(g=>g.cat==='aviation')],['Adrenaline Rush',games.filter(g=>['action','racing'].includes(g.cat)).slice(0,10)],['Sports Arena',games.filter(g=>g.cat==='sports')],['Epic Worlds',games.filter(g=>['adventure','fantasy'].includes(g.cat)).slice(0,10)],['New Releases',games.slice(30,40)]];
let selected='all',query='',myList=new Set();const rows=document.getElementById('gameRows'),empty=document.getElementById('emptyState'),modal=document.getElementById('gameModal');
function card(g,rank){return `<article class="game-card ${rank?'ranked':''}" data-title="${g.title.toLowerCase()}">${rank?`<span class="rank">${rank}</span>`:''}<div><img src="${g.img}" alt="${g.title} game artwork" loading="lazy"><div class="card-info"><div class="card-top"><strong>${g.title}</strong><button class="round add" data-title="${g.title}" aria-label="Add ${g.title} to My List">${myList.has(g.title)?'✓':'＋'}</button></div><div class="tags">${g.tags.split(' • ').map(x=>`<span>${x}</span>`).join('')}</div></div></div></article>`}
function render(){let shown=0;rows.innerHTML=rowDefs.map(([name,list])=>{const filtered=list.filter(g=>(selected==='all'||g.cat===selected)&&(`${g.title} ${g.tags}`.toLowerCase().includes(query)));if(!filtered.length)return'';shown+=filtered.length;return `<section class="game-row" id="${name.includes('Aviation')?'aviation':name.includes('New')?'new':''}"><div class="row-head"><h2>${name}</h2><span>Explore all ›</span></div><div class="slider">${filtered.map((g,i)=>card(g,name.startsWith('Top 10')?i+1:0)).join('')}</div></section>`}).join('');empty.hidden=shown>0;bindCards()}
function bindCards(){document.querySelectorAll('.game-card').forEach(el=>el.addEventListener('click',e=>{if(e.target.closest('.add'))return;openGame(games.find(g=>g.title.toLowerCase()===el.dataset.title))}));document.querySelectorAll('.add').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();toggleList(b.dataset.title)}))}
function toggleList(title){myList.has(title)?myList.delete(title):myList.add(title);const count=document.getElementById('listCount');if(count)count.textContent=myList.size;showToast(myList.has(title)?`${title} added to My List`:`${title} removed`);render()}
function openGame(g){document.getElementById('modalImage').src=g.img;document.getElementById('modalImage').alt=`${g.title} game artwork`;document.getElementById('modalTitle').textContent=g.title;document.getElementById('modalText').textContent=g.desc;modal.querySelector('.add').dataset.title=g.title;modal.querySelector('.add').textContent=myList.has(g.title)?'✓':'＋';modal.classList.add('open');document.body.style.overflow='hidden'}
function closeModal(){modal.classList.remove('open');document.body.style.overflow=''}function showToast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>x.classList.remove('show'),2200)}
document.querySelectorAll('.genre-bar button').forEach(b=>b.onclick=()=>{document.querySelector('.genre-bar .active').classList.remove('active');b.classList.add('active');selected=b.dataset.filter;render()});document.getElementById('searchInput').oninput=e=>{query=e.target.value.trim().toLowerCase();render()};document.querySelector('.menu').onclick=()=>document.querySelector('.nav-menu').classList.toggle('open');document.querySelectorAll('[data-auth]').forEach(button=>button.onclick=()=>showToast(button.dataset.auth==='login'?'Login selected':'Sign Up selected'));modal.querySelector('.close').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};modal.querySelector('.add').onclick=e=>{toggleList(e.currentTarget.dataset.title);e.currentTarget.textContent=myList.has(e.currentTarget.dataset.title)?'✓':'＋'};document.getElementById('heroInfo').onclick=()=>openGame(games[0]);document.getElementById('heroPlay').onclick=()=>showToast('Launching Sky Dominion…');addEventListener('scroll',()=>document.querySelector('.stream-nav').classList.toggle('scrolled',scrollY>30));addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});render();
